name: release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: docker://ferrarimarco/github-changelog-generator --user rndmh3ro --project ansible-test-framework --token ${{ secrets.GITHUB_TOKEN }}
